export const signupErrorActionTypes = {
    SET_FIRSTNAME_ERROR: "SET_FIRSTNAME_ERROR",
    SET_LASTNAME_ERROR: "SET_LASTNAME_ERROR",
    SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
    SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
    SET_CONFIRM_PASSWORD_ERROR: "SET_CONFIRM_PASSWORD_ERROR",
    SET_AGREE_ERROR: "SET_AGREE_ERROR",
    RESET_SIGNUP_ERRORS: "RESET_SIGNUP_ERRORS",
};

export const signupUserActiontypes = {
    SET_FIRSTNAME: "SET_FIRSTNAME",
    SET_LASTNAME: "SET_LASTNAME",
    SET_EMAIL: "SET_EMAIL",
    SET_PASSWORD: "SET_PASSWORD",
    SET_CONFIRM_PASSWORD: "SET_CONFIRM_PASSWORD",
    SET_AGREE_TO: "SET_AGREE_TO",
    RESET_NEW_USER_DATA: "RESET_NEW_USER_DATA",
};

export const authActionTypes = {
    SET_AUTH: "SET_AUTH",
    SET_LOGIN_ERROR: "SET_LOGIN_ERROR",
    SET_SIGNUP_ERROR: "SET_SIGNUP_ERROR",
    SET_AUTH_LOGOUT: "SET_AUTH_LOGOUT",
};

export const noteActionTypes = {
    SET_EDIT_NOTE: "SET_EDIT_NOTE",
    SET_NOTES: "SET_NOTES",
    SET_INPUT_NOTE_VALUES: "SET_INPUT_NOTE_VALUES",
    UPDATED_NOTES_ARCHIVES: "UPDATED_NOTES_ARCHIVES",
    SET_ARCHIVES: "SET_ARCHIVES",
    SET_TRASH: "SET_TRASH",
    UPDATED_NOTES_TRASH: "UPDATED_NOTES_TRASH",
    UPDATED_ARCHIVES_TRASH: "UPDATED_ARCHIVES_TRASH",
    SET_NOTES_TRASH_ARCHIVE: "SET_NOTES_TRASH_ARCHIVE",
};

export const tagsActionTypes = {
    SET_TAG_INPUT: "SET_TAG_INPUT",
    CREATE_TAG: "CREATE_TAG",
    REMOVE_TAG: "REMOVE_TAG",
    UPDATE_TAG_STATE: "UPDATE_TAG_STATE",
    RESET_GLOBAL_TAG_STATES: "RESET_GLOBAL_TAG_STATES",
    SET_GLOBAL_TAGS_LIST: "SET_GLOBAL_TAGS_LIST",
};
